# Generated by Django 2.1.4 on 2019-01-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20181225_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='upload',
            field=models.ImageField(default='uploads/default/default.png', upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
