# Generated by Django 2.1.5 on 2019-01-22 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20190122_0041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-date']},
        ),
    ]
