# Generated by Django 2.1.4 on 2018-12-25 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_remove_answer_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
    ]
